### ISSUE TITLE
Any plans to update for Meteor 1.0.4.1?

### ISSUE THREAD

**Issue by shkomg** [splendido/meteor-accounts-meld#11]
Hi,

i have faced the error, possibly related to recent update in Meteor minimongo (as I'm researched it is possibly about ```updateEmails```:

```
=> Client modified -- refreshing           
I20150319-22:18:40.051(2)? Exception in onLogin callback: MongoError: '$set' is empty. You must specify a field like so: {$mod: {<field>: ...}}
I20150319-22:18:40.051(2)?     at Object.Future.wait (/home/shkomg/.meteor/packages/meteor-tool/.1.0.43.171erx9++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:398:15)         
I20150319-22:18:40.051(2)?     at [object Object].<anonymous> (packages/meteor/helpers.js:119:1)
I20150319-22:18:40.051(2)?     at [object Object].MongoConnection.(anonymous function) [as update] (packages/mongo/mongo_driver.js:678:1)
I20150319-22:18:40.051(2)?     at [object Object].Mongo.Collection.(anonymous function) (packages/mongo/collection.js:575:1)
I20150319-22:18:40.052(2)?     at [object Object].Mongo.Collection.(anonymous function) [as update] (packages/aldeed:collection2/collection2.js:159:1)                                    
I20150319-22:18:40.052(2)?     at updateEmails (packages/splendido:accounts-meld/lib/accounts-emails-field/lib/accounts-emails-field.js:88:1)                                             
I20150319-22:18:40.052(2)?     at Package (packages/splendido:accounts-meld/lib/accounts-meld-hooks.js:10:1)
I20150319-22:18:40.052(2)?     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:108:1)
I20150319-22:18:40.052(2)?     at packages/meteor/dynamics_nodejs.js:121:1
I20150319-22:18:40.053(2)?     at packages/accounts-base/accounts_server.js:87:1
I20150319-22:18:40.053(2)?     - - - - -                                                                                                                                                  
I20150319-22:18:40.053(2)?     at Object.toError (/home/shkomg/.meteor/packages/mongo/.1.1.0.1q3w6s6++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/utils.js:114:11)    
I20150319-22:18:40.053(2)?     at /home/shkomg/.meteor/packages/mongo/.1.1.0.1q3w6s6++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/collection/core.js:577:27           
I20150319-22:18:40.054(2)?     at /home/shkomg/.meteor/packages/mongo/.1.1.0.1q3w6s6++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/db.js:1195:7                        
I20150319-22:18:40.054(2)?     at /home/shkomg/.meteor/packages/mongo/.1.1.0.1q3w6s6++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/db.js:1903:9                        
I20150319-22:18:40.054(2)?     at Server.Base._callHandler (/home/shkomg/.meteor/packages/mongo/.1.1.0.1q3w6s6++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/base.js:453:41)                                    
I20150319-22:18:40.054(2)?     at /home/shkomg/.meteor/packages/mongo/.1.1.0.1q3w6s6++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/server.js:487:18         
I20150319-22:18:40.054(2)?     at [object Object].MongoReply.parseBody (/home/shkomg/.meteor/packages/mongo/.1.1.0.1q3w6s6++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)                             
I20150319-22:18:40.055(2)?     at [object Object].<anonymous> (/home/shkomg/.meteor/packages/mongo/.1.1.0.1q3w6s6++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/server.js:445:20)                                 
I20150319-22:18:40.056(2)?     at [object Object].emit (events.js:95:17)
I20150319-22:18:40.056(2)?     at [object Object].<anonymous> (/home/shkomg/.meteor/packages/mongo/.1.1.0.1q3w6s6++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:207:13) 
```
Your help is really needed. 

Thank you.

**Comment by splendido** [comment]
I'm up to it right now...

Could you please explain the sequence of actions to be done to reproduce the error?


Tnx!

**Comment by shkomg** [comment]
@splendido sorry - that's not in accounts-meld, it works perfectly with new Meteor, if I've checked everything. This is in alanning:roles - here https://github.com/alanning/meteor-roles/issues/91

**Comment by shkomg** [comment]
@splendido oops, sorry, not yet successful in localization & reproduction of that error. In sample code all works well, when crashed in main app :(

**Comment by splendido** [comment]
I was not able to reproduce your problem so far...
Playing a bit with an updated version of [test-accounts-meld.meteor.com](http://test-accounts-meld.meteor.com/) everything seems working good.

...I'm no up to make package's tests working again on latest Meteor release.

**Comment by shkomg** [comment]
@splendido I've found what is happening: 
- in updateEmails in accounts-emails-field you create new field registered_emails in user document
- I use simpleSchema for user doc & don't have registered_emails in the schema - this now leads to the error
- somehow before update of the Meteor the error wasn't displayed & everything worked fine (no additional filed were created in the user doc)

So I've added registered_emails to the user doc schema & all works fine now.

**Comment by splendido** [comment]
Might still be something to check on my side!
I'd support the creation of the field when it is not preset ;-)
...I guess I have to check some `Meteor.users.update({...}, {$set: something})` and see if I pass `something` empty which could rise the error you reported at the begin...

**Comment by shkomg** [comment]
sure, that 'd be great!

2015-03-23 14:20 GMT+02:00 Luca Mussi <notifications@github.com>:

> Might still be something to check on my side!
> I'd support the creation of the field when it is not preset ;-)
> ...I guess I have to check some Meteor.users.update({...}, {$set:
> something}) and see if I pass something empty which could rise the error
> you reported at the begin...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/splendido/meteor-accounts-meld/issues/11#issuecomment-84969928>
> .
>



-- 
Best regards

Serhiy Khvashchuk

**Comment by athenawisdoms** [comment]
@shkomg I'm getting the same error and using SimpleSchema too! What did you add to your schema to get it to work? Thanks!!

**Comment by shkomg** [comment]
@athenawisdoms  I've added ```registered_emails``` field to the user doc schema & that's it

**Comment by richsilv** [comment]
To clarify a little, here's what you need in your schema:

```
  'registered_emails': {
    type: [Object],
    blackbox: true,
    optional: true
  }
```
