### ISSUE TITLE
Clearer doc about what services can be melded?

### ISSUE THREAD

**Issue by steph643** [splendido/meteor-accounts-meld#12]
I have just tried to log-in using Twitter and realized the account is not melded. 

So I went deeper into your doc, but I am still not sure. Can you please confirm the following?:
- A Twitter account cannot be melded because it does not provide any email field.
- A Github account cannot be melded because it does not provide a "verified email" field.
- A Google account can be melded because it provides a "verified email" field.
- Facebook and LinkedIn accounts can be melded because, although they do not provide a "verified email" field, the "email" field they provide is inevitably "verified" due to Facebook and LinkedIn enrollment processes.

If you confirm this, I think the doc should be updated to make this immediately understandable.

**Comment by splendido** [comment]
Yes that's all correct!

...if the need to get only accesses with verified email is not mandatory, you can add some functionality to your app and permit the user to verify her email after having signed up.

But if you don't want the same user to create different accounts you should not use services which don't tell you whether the email is verified or not...

Could you please propose a PR to put this things clearer?
It seems you eventually got it right, so I guess you can propose good changes!

Thanks :-)

**Comment by steph643** [comment]
I started something, please see the PR.

I think your decision of basing the melding process on the verified email is the right one.

**Comment by splendido** [comment]
:+1:
