### ISSUE TITLE
LinkedIn support

### ISSUE THREAD

**Issue by steph643** [splendido/meteor-accounts-meld#14]
The doc mentions LinkedIn as a supported service. But looking in the usual Meteor resources, I can find no recent information about how LinkedIn can be added as a service (including compatibility with useraccounts packages).
Any remark or advice that could be added to the doc?

**Comment by splendido** [comment]
to get the LinkedIn OAuth service, it should be enough to add [pauli:accounts-linkedin](https://atmospherejs.com/pauli/accounts-linkedin) package with

```shell
meteor add pauli:accounts-linkedin
```

and configure the service on the server side with something like [this](https://github.com/meteor-useraccounts/boilerplates/blob/master/ionic/server/lib/config/accounts.js#L41-51)
