### ISSUE TITLE
Feature request: show more respect to the elders

### ISSUE THREAD

**Issue by steph643** [splendido/meteor-accounts-meld#16]
When melding two users, the older user is deleted. The new user is updated with the old user services, but it seems the old user `_id` is lost.
This is unfortunate, because the old user `_id` might already be used in other places to associate the user with some other data. 
In my application for example, I have a collection that associates a `userId` with a `postId`. Each time an account is melded, this creates an orphan record (i.e. linked to a deleted user).
Could the old user `_id` be preserved when melding two users?

**Comment by splendido** [comment]
the reason for this is to keep the current user logged in (hence saving some roundtrip communication  to the server and prevent the current user to see weird blinks on the page is visiting, not to mention what could happen if her is on a *protected* page...).

To address your very same use case, a number of callbacks were put in place to let you migrate *old* documents to the new user.

Lets check out [meldUserCallback](https://github.com/splendido/meteor-accounts-meld#meldusercallback) and [meldDBCallback](https://github.com/splendido/meteor-accounts-meld#melddbcallback) (the one you're interested in).

Hope all this makes sense

**Comment by steph643** [comment]
Makes perfect sense, thanks.
