### ISSUE TITLE
meldUserCallback: doc not clear to me

### ISSUE THREAD

**Issue by steph643** [splendido/meteor-accounts-meld#17]
The doc says:
```javascript
meldUserCallback = function(src_user, dst_user){
    // modify the dst_user object here (in place) if there is 
    // something inside src_user that must be preserved
};
```
and:
>this is how it is called:
var meldedUser = meldUserCallback(src_user, dst_user);

This sounds contradictory to me. Should I modify `dst_user` in place or return the keys I want you to copy into `dst_user`?

Also:
>In particular the line:
meldedUser = _.omit(meldedUser, '_id', 'services', 'emails', 'registered_emails');
ensures that any accidental modification to sensitive fields will be neglected...

I am not sure accidental modification is prevented if I modify `dst_user` in place.

**Comment by splendido** [comment]
@steph643 you're right!
[These](https://github.com/splendido/meteor-accounts-meld/blob/master/lib/accounts-meld-server.js#L190-197) are the lines you're talking about...

I guess the documentation was left behind to an old version
