### ISSUE TITLE
Strange error (Meteor 1.2.0.2)

### ISSUE THREAD

**Issue by shactdeveloper** [splendido/meteor-accounts-meld#26]
Hi, back on Meteor 1.1, this package worked fine for me... now, after update, I get this error when any user logs in:

I20151005-23:51:15.821(-3)? Exception in onLogin callback: Error: When the modifier option is true, validation object must have at least one operator
I20151005-23:51:15.821(-3)?     at checkModifier (packages/aldeed_simple-schema/packages/aldeed_simple-schema.js:2293:1)
I20151005-23:51:15.821(-3)?     at doValidation1 (packages/aldeed_simple-schema/packages/aldeed_simple-schema.js:2343:1)
I20151005-23:51:15.822(-3)?     at doValidation (packages/aldeed_simple-schema/packages/aldeed_simple-schema.js:2758:1)
I20151005-23:51:15.822(-3)?     at SimpleSchemaValidationContext.simpleSchemaValidationContextValidate [as validate] (packages/aldeed_simple-schema/packages/aldeed_simple-schema.js:2793:1)
I20151005-23:51:15.822(-3)?     at [object Object].doValidate (packages/aldeed_collection2/packages/aldeed_collection2.js:372:1)
I20151005-23:51:15.822(-3)?     at [object Object].Mongo.Collection.(anonymous function) [as update] (packages/aldeed_collection2/packages/aldeed_collection2.js:177:1)
I20151005-23:51:15.822(-3)?     at updateEmails (packages/splendido_accounts-emails-field/packages/splendido_accounts-emails-field.js:171:1)
I20151005-23:51:15.822(-3)?     at runAndHandleExceptions (packages/callback-hook/hook.js:133:1)
I20151005-23:51:15.822(-3)?     at packages/callback-hook/hook.js:140:1
I20151005-23:51:15.822(-3)?     at accounts_server.js:165:5

**Comment by splendido** [comment]
looking at the call stack, it seem it might be a problem with `aldeed:collection2`

> I20151005-23:51:15.822(-3)? at [object Object].doValidate packages/aldeed_collection2/packages/aldeed_collection2.js:372:1)

Might this be connected with your schema?
See also [this SO post](http://stackoverflow.com/questions/30032315/uncaught-error-when-the-modifier-option-is-true-validation-object-must-have-at)

**Comment by shactdeveloper** [comment]
Hi! fixed it by adding registered_emails to my user schema
somehow this error was not showing up on meteor 1.1...

**Comment by splendido** [comment]
I see. I'm sorry you're not the first one hitting this.
The need to extend the schema for the user collection is mentioned [here](https://github.com/splendido/meteor-accounts-emails-field/#usage) but I guess we should report it also among the docs for `accounts-meld`

**Comment by splendido** [comment]
See 32c143eeb718ee22de0598ff78df434be3ea28e2
