### ISSUE TITLE
Allow server-side calling of Accounts.updateOrCreateUserFromExternalService

### ISSUE THREAD

**Issue by loredanacirstea** [splendido/meteor-accounts-meld#29]
First, thank you for the package.

Second:
I have to provide an API sign up with a Google JSON Web Token in my web app - for a mobile app. 
It would have been very useful to be able to call `Accounts.updateOrCreateUserFromExternalService` from the server, with my user data and also get melded accounts.

Issue: 

https://github.com/splendido/meteor-accounts-meld/blob/eb14c4ce9f9be785e95e4a5ae4b59e0cd790231c/lib/accounts-meld-server.js#L493

You use `currentUser = Meteor.user()` , which gives the following error:

```
Error in method "/api/setuser/", Error: Error: Meteor.userId can only be invoked in method calls. Use this.userId in publish functions.
    at Object.Meteor.userId (packages/accounts-base/accounts_server.js:19:1)
    at Object.Meteor.user (packages/accounts-base/accounts_server.js:24:1)
    at Object.updateOrCreateUserFromExternalService (packages/splendido:accounts-meld/lib/accounts-meld-server.js:495:1)
    at Object.HTTP.methods./api/setuser.post (app/server/api/user.js:159:28)
    at packages/cfs:http-methods/http.methods.server.api.js:574:1
```

Because you override the original method, I can't use it. Can you provide an export of the original ? It would of course be great if we could meld accounts from the server.

**Comment by splendido** [comment]
Would [this](https://github.com/splendido/meteor-accounts-meld/issues/25#issuecomment-146301570) be useful for you to meld accounts from the server side?

**Comment by loredanacirstea** [comment]
Sorry for the big delay in answering, I only got to this issue today.

https://github.com/splendido/meteor-accounts-meld/issues/25 is helpful for melding accounts from the server, but you have to have the accounts already.

My issue was that I could not actually create an account with `Accounts.updateOrCreateUserFromExternalService`, from a server API method. I don't know how else to do this, without getting more into the internals of `accounts-base`  

So, I modified you package locally at https://github.com/splendido/meteor-accounts-meld/blob/eb14c4ce9f9be785e95e4a5ae4b59e0cd790231c/lib/accounts-meld-server.js#L493

```
var currentUser
	if(!Meteor.isServer)
		currentUser = Meteor.user()
	else
		currentUser = null
```

I am closing this issue now, but maybe you can take this into account for the package.

Thank you!
